# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '28th_BESOPT_5thWeek_Seminar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 28th_BESOPT_5thWeek_Seminar
  pod 'lottie-ios'
end
